export enum WordType {
    NOUN = "NOUN",
    VERB = "VERB",
    ADJECTIVE = "ADJECTIVE",
    ADVERB = "ADVERB",
    PREPOSITION = "PREPOSITION",
    CONJUNCTION = "CONJUNCTION",
    INTERJECTION = "INTERJECTION",
    PRONOUN = "PRONOUN",
    DETERMINER = "DETERMINER",
    EXCLAMATION = "EXCLAMATION"
}